// data/programData.js

export const programCards = [
  {
    id: 1,
    title: "Advanced Data Science & AI Master Certification",
    description: "Achieve Full-Stack AI Skills and Complete Industry Projects",
    why: [
      "Build AI-powered applications",
      "Master prompt engineering techniques",
    ],
    keySkills: ["ChatGPT", "Claude", "Prompt Engineering"],
    duration: "16 Weeks",
    level: "Advanced",
    eligibility: "Working professionals with 2+ years experiences",
    brochureUrl: "#",
    theme: "purple",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/new-UI/ibm-microsoft+(1).webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/new-UI/icon_pur.webp",
  },

  {
    id: 2,
    title: "Data Analytics and Business Analytics with Generative AI",
    description: "Master Data-Driven Insights and Analytics with Gen AI",
    why: [
      "Build AI-powered applications",
      "Master prompt engineering techniques",
    ],
    keySkills: ["ChatGPT", "Claude", "Prompt Engineering"],
    duration: "16 Weeks",
    level: "Advanced",
    eligibility: "Working professionals with 2+ years experiences",
    brochureUrl: "#",
    theme: "chocolateOrange",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/new-UI/ibm-microsoft+(1).webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/new-UI/icon_pur.webp",
  },
  {
    id: 3,
    title: "DevOps Engineering & Cloud Master",
    description: "Automate deployments & manage cloud infrastructure at scale",
    why: ["Master containerization", "Implement CI/CD Pipelines"],
    keySkills: ["Docker", "CI/CD", "Kubernetes"],
    duration: "22 Weeks",
    level: "Expert",
    eligibility: "Working professionals with 2+ years experiences",
    brochureUrl: "#",
    theme: "green",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/new-UI/ibm-microsoft+(1).webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/learnbay_v4/Homepage/course_section/devops_icon.png",
  },
  {
    id: 4,
    title: "Cybersecurity & Digital Defense Master",
    description:
      "Protect digital assets & build secure system from the ground up",
    why: ["Master ethical hacking techniques", "Design secure systems"],
    keySkills: ["Penetration Testing", "Network Security"],
    duration: "16 Weeks",
    level: "Advanced",
    eligibility: "Working professionals with 2+ years experiences",
    brochureUrl: "#",
    theme: "red",
    logo: "https://d32and0ii3b8oy.cloudfront.net/web/s3_main/new-UI/ibm-microsoft+(1).webp",
    icon: "https://d32and0ii3b8oy.cloudfront.net/web/learnbay_v4/Homepage/course_section/cyber_security_cion.png",
  },
];
